Algoritmo "Orientação a Objetos"

tipo

cadastroCliente = registro
                nome: caractere
                rg: caractere
                idade: inteiro
fimregistro

Var

cliente1: cadastroCliente

Inicio

Escreval("Digite seu nome: ")
leia(cliente1.nome)

Escreval("Digite seu rg: ")
leia(cliente1.rg)

Escreval("Digite sua idade: ")
leia(cliente1.idade)

Escreval("Nome ",cliente1.nome," o rg é ",cliente1.rg," sua idade é ",cliente1.idade," ano(s).")

Fimalgoritmo