Algoritmo "Aleatorio"

Var
   aleatorioMaximo, aleatorioMinimo, incrementro, i : inteiro

Inicio
      repita
      aleatorio 1,100
                leia(aleatorioMaximo)
                leia(aleatorioMinimo)
      aleatorio off
      ate aleatorioMaximo >= aleatorioMinimo
      limpatela
      
      aleatorio 1,5
                leia(incrementro)
      aleatorio off
      
      para i de aleatorioMinimo ate aleatorioMaximo passo incrementro faca
          escreval(i)
      fimpara

Fimalgoritmo