Algoritmo "Escolha"

Var
   voto: inteiro
   
Inicio
      Escreval("Digite seu voto:")
      leia(voto)
      
      Escolha voto
              caso 20
                   Escreval("Você votou no Fulano.")
              caso 30
                   Escreval("Você votou no Ciclano.")
              caso 40
                   Escreval("Você votou no Beutrano.")
              outrocaso
                       Escreval("Voto nulo.")
              
      fimescolha
      

Fimalgoritmo